services:
  # VPN
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15.3.0
    environment:
      WG_DEVICE: eth0
      INIT_ENABLED: true
      INIT_USERNAME: ${VPN_GUI_USERNAME:-admin}
      INIT_PASSWORD: ${VPN_GUI_PASSWORD}
      INIT_HOST: ${VPN_ENDPOINT}
      INIT_PORT: 51820
      INIT_DNS: ${VPN_DNS:-} # WARN: Remove empty DNS entry and add keepalive 25 via GUI
      INIT_IPV4_CIDR: "172.16.14.0/24"
      INIT_IPV6_CIDR: "2001:0DB8::/32"
      INIT_ALLOWED_IPS: "172.16.14.0/24,2001:0DB8::/32,172.16.15.0/24"
    volumes:
      - type: volume
        source: wireguard-conf-vol
        target: /etc/wireguard
        volume:
          nocopy: false
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
    ports:
      - "51820:51820/udp"
    networks:
      wireguard-2-internet:
        driver_opts:
          com.docker.network.endpoint.ifname: eth0
      wireguard-2-internal:
        driver_opts:
          com.docker.network.endpoint.ifname: eth1
        ipv4_address: 172.16.15.253
      traefik-2-wireguard:
        driver_opts:
          com.docker.network.endpoint.ifname: eth2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-wireguard"
      - "traefik.http.routers.wireguard.rule=Host(`${VPN_DOMAIN}`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      # - "traefik.http.middlewares.traefik-real-ip.plugin.traefik-real-ip.excludednets=[]" # WARN: Defined only once, other containers can use this
    restart: unless-stopped

  # Reverse proxy
  traefik:
    image: docker.io/library/traefik:v3.6.6
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entrypoints.web.http.middlewares=traefik-real-ip@docker"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3"
      - "--entrypoints.websecure.http3.advertisedPort=443"
      # - "--entrypoints.websecure.http.middlewares=traefik-real-ip@docker"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # - "--experimental.plugins.traefik-real-ip.modulename=github.com/jramsgz/traefik-real-ip"
      # - "--experimental.plugins.traefik-real-ip.version=v1.0.7"
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_API_TOKEN}
      CF_ZONE_API_TOKEN: ${TRAEFIK_CF_API_TOKEN}
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: traefik-acme-vol
        target: /acme
        volume:
          nocopy: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - "127.0.0.1:80:80/tcp" # WARN: Accessible on localhost only (SSH tunnel)
      - "127.0.0.1:443:443/tcp" # WARN: Accessible on localhost only (SSH tunnel)
      - "127.0.0.1:443:443/udp" # WARN: Accessible on localhost only (SSH tunnel)
    networks:
      traefik-2-internet:
      traefik-2-wireguard:
      traefik-2-lldap:
      traefik-2-authelia:
      traefik-2-umami:
      traefik-2-vaultwarden:
      traefik-2-sftpgo:
        ipv4_address: 172.19.0.253
      traefik-2-vikunja:
        ipv4_address: 172.19.1.253
      cloudflared-2-traefik:
      wireguard-2-internal:
        ipv4_address: 172.16.15.1 # WARN: Makes ports above accessible over VPN
    restart: unless-stopped

  cloudflared:
    image: docker.io/cloudflare/cloudflared:2026.7.2
    command: ["tunnel", "--no-autoupdate", "run"]
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      cloudflared-2-internet:
      cloudflared-2-traefik:
    restart: unless-stopped

  # IDP
  lldap-postgres:
    image: docker.io/library/postgres:16.9
    environment:
      POSTGRES_DB: ${LLDAP_POSTGRES_DB:-lld}
      POSTGRES_USER: ${LLDAP_POSTGRES_USER:-lld}
      POSTGRES_PASSWORD: ${LLDAP_POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: lldap-postgres-vol
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    networks:
      - lldap-2-postgres
      - lldap-pgdumper-2-postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${LLDAP_POSTGRES_USER:-lld} -d ${LLDAP_POSTGRES_DB:-lld}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  lldap-pgdumper:
    image: docker.io/martlark/pg_dump:16.1
    environment:
      CRON_SCHEDULE: "1 * * * *"
      RETAIN_COUNT: 1
      PGHOST: "lldap-postgres"
      POSTGRES_DB: ${LLDAP_POSTGRES_DB:-lld}
      PGUSER: ${LLDAP_POSTGRES_USER:-lld}
      POSTGRES_PASSWORD: ${LLDAP_POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: /var/stor/lldap/pgdump
        target: /dump
    networks:
      - lldap-pgdumper-2-postgres
    restart: unless-stopped
    depends_on:
      lldap-postgres:
        condition: service_healthy
        restart: true

  lldap-restic:
    image: ghcr.io/lobaro/restic-backup-docker:v1.4.2
    environment:
      BACKUP_CRON: "12 * * * *"
      RESTIC_FORGET_ARGS: "--prune --keep-last 3 --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 6"
      RESTIC_PASSWORD: "${LLDAP_RESTIC_ENCRYPTION_KEY}"
      RESTIC_REPOSITORY: "s3:https://${LLDAP_RESTIC_S3_ENDPOINT}/${LLDAP_RESTIC_S3_BUCKET}"
      AWS_ACCESS_KEY_ID: "${LLDAP_RESTIC_S3_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${LLDAP_RESTIC_S3_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: /var/stor/lldap
        target: /data/backup
        read_only: true
    networks:
      - lldap-restic-2-internet
    restart: unless-stopped

  lldap:
    image: docker.io/lldap/lldap:v0.6.2
    environment:
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_KEY_SEED: ${LLDAP_KEY_SEED}
      LLDAP_LDAP_BASE_DN: ${LLDAP_BASE_DN}
      LLDAP_LDAP_USER_PASS: ${LLDAP_ADMIN_PASSWORD}
      LLDAP_DATABASE_URL: "postgres://${LLDAP_POSTGRES_USER:-lld}:${LLDAP_POSTGRES_PASSWORD}@lldap-postgres/${LLDAP_POSTGRES_DB:-lld}"
    networks:
      - lldap-2-internet
      - lldap-2-postgres
      - traefik-2-lldap
      - authelia-2-lldap
    restart: unless-stopped
    depends_on:
      lldap-postgres:
        condition: service_healthy
        restart: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-lldap"
      - "traefik.http.routers.lldap.rule=Host(`${LLDAP_DOMAIN}`)"
      - "traefik.http.routers.lldap.entrypoints=websecure"
      - "traefik.http.routers.lldap.tls=true"
      - "traefik.http.routers.lldap.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lldap.service=lldap"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"

  # SSO
  authelia-valkey:
    image: docker.io/valkey/valkey:8.1.3
    command:
      [
        "valkey-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${AUTHELIA_VALKEY_PASSWORD}",
      ]
    volumes:
      - type: volume
        source: authelia-valkey-vol
        target: /data
        volume:
          nocopy: false
    networks:
      - authelia-2-valkey
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${AUTHELIA_VALKEY_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  authelia-postgres:
    image: docker.io/library/postgres:16.9
    environment:
      POSTGRES_DB: ${AUTHELIA_POSTGRES_DB:-atl}
      POSTGRES_USER: ${AUTHELIA_POSTGRES_USER:-atl}
      POSTGRES_PASSWORD: ${AUTHELIA_POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: authelia-postgres-vol
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    networks:
      - authelia-2-postgres
      - authelia-pgdumper-2-postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTHELIA_POSTGRES_USER:-atl} -d ${AUTHELIA_POSTGRES_DB:-atl}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  authelia-pgdumper:
    image: docker.io/martlark/pg_dump:16.1
    environment:
      CRON_SCHEDULE: "1 * * * *"
      RETAIN_COUNT: 1
      PGHOST: "authelia-postgres"
      POSTGRES_DB: ${AUTHELIA_POSTGRES_DB:-atl}
      PGUSER: ${AUTHELIA_POSTGRES_USER:-atl}
      POSTGRES_PASSWORD: ${AUTHELIA_POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: /var/stor/authelia/pgdump
        target: /dump
    networks:
      - authelia-pgdumper-2-postgres
    restart: unless-stopped
    depends_on:
      authelia-postgres:
        condition: service_healthy
        restart: true

  authelia-restic:
    image: ghcr.io/lobaro/restic-backup-docker:v1.4.2
    environment:
      BACKUP_CRON: "12 * * * *"
      RESTIC_FORGET_ARGS: "--prune --keep-last 3 --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 6"
      RESTIC_PASSWORD: "${AUTHELIA_RESTIC_ENCRYPTION_KEY}"
      RESTIC_REPOSITORY: "s3:https://${AUTHELIA_RESTIC_S3_ENDPOINT}/${AUTHELIA_RESTIC_S3_BUCKET}"
      AWS_ACCESS_KEY_ID: "${AUTHELIA_RESTIC_S3_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AUTHELIA_RESTIC_S3_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: /var/stor/authelia
        target: /data/backup
        read_only: true
    networks:
      - authelia-restic-2-internet
    restart: unless-stopped

  authelia:
    image: docker.io/authelia/authelia:4.39.14
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: true
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: "lldap"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: "ldap://lldap:3890"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ${LLDAP_BASE_DN}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "UID=authelia,OU=people,${LLDAP_BASE_DN}"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${AUTHELIA_LDAP_PASSWORD}
      AUTHELIA_TOTP_ISSUER: ${AUTHELIA_DOMAIN}
      AUTHELIA_PASSWORD_POLICY_ZXCVBN_ENABLED: true
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_SESSION_REDIS_HOST: "authelia-valkey"
      AUTHELIA_SESSION_REDIS_USERNAME: "default"
      AUTHELIA_SESSION_REDIS_PASSWORD: ${AUTHELIA_VALKEY_PASSWORD}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_STORAGE_POSTGRES_ADDRESS: "tcp://authelia-postgres:5432"
      AUTHELIA_STORAGE_POSTGRES_DATABASE: ${AUTHELIA_POSTGRES_DB:-atl}
      AUTHELIA_STORAGE_POSTGRES_USERNAME: ${AUTHELIA_POSTGRES_USER:-atl}
      AUTHELIA_STORAGE_POSTGRES_PASSWORD: ${AUTHELIA_POSTGRES_PASSWORD}
      AUTHELIA_NOTIFIER_SMTP_ADDRESS: ${AUTHELIA_SMTP_ADDRESS}
      AUTHELIA_NOTIFIER_SMTP_USERNAME: ${AUTHELIA_SMTP_USERNAME}
      AUTHELIA_NOTIFIER_SMTP_PASSWORD: ${AUTHELIA_SMTP_PASSWORD}
      AUTHELIA_NOTIFIER_SMTP_SENDER: ${AUTHELIA_SMTP_SENDER}
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ${AUTHELIA_HMAC_SECRET}
    volumes:
      - type: bind
        source: ./config/authelia.yml
        target: /config/configuration.yml
        read_only: true
    networks:
      - authelia-2-internet
      - authelia-2-valkey
      - authelia-2-postgres
      - authelia-2-lldap
      - traefik-2-authelia
    restart: unless-stopped
    depends_on:
      authelia-valkey:
        condition: service_healthy
        restart: true
      authelia-postgres:
        condition: service_healthy
        restart: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-authelia"
      - "traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authelia.service=authelia"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"

  # Analytics
  umami-postgres:
    image: docker.io/library/postgres:16.9
    environment:
      POSTGRES_DB: ${UMAMI_DATABASE_DB:-um}
      POSTGRES_USER: ${UMAMI_DATABASE_USER:-um}
      POSTGRES_PASSWORD: ${UMAMI_DATABASE_PASSWORD}
    volumes:
      - type: volume
        source: umami-postgres-vol
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    networks:
      - umami-2-postgres
      - umami-pgdumper-2-postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${UMAMI_DATABASE_USER:-um} -d ${UMAMI_DATABASE_DB:-um}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  umami-pgdumper:
    image: docker.io/martlark/pg_dump:16.1
    environment:
      CRON_SCHEDULE: "1 * * * *"
      RETAIN_COUNT: 1
      PGHOST: "umami-postgres"
      POSTGRES_DB: ${UMAMI_DATABASE_DB:-um}
      PGUSER: ${UMAMI_DATABASE_USER:-um}
      POSTGRES_PASSWORD: ${UMAMI_DATABASE_PASSWORD}
    volumes:
      - type: bind
        source: /var/stor/umami/pgdump
        target: /dump
    networks:
      - umami-pgdumper-2-postgres
    restart: unless-stopped
    depends_on:
      umami-postgres:
        condition: service_healthy
        restart: true

  umami-restic:
    image: ghcr.io/lobaro/restic-backup-docker:v1.4.2
    environment:
      BACKUP_CRON: "52 * * * *" # Every hour at 52nd minute
      RESTIC_FORGET_ARGS: "--prune --keep-last 3 --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"
      RESTIC_PASSWORD: "${UMAMI_RESTIC_ENCRYPTION_KEY}"
      RESTIC_REPOSITORY: "s3:https://${UMAMI_RESTIC_S3_ENDPOINT}/${UMAMI_RESTIC_S3_BUCKET}"
      AWS_ACCESS_KEY_ID: "${UMAMI_RESTIC_S3_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${UMAMI_RESTIC_S3_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: /var/stor/umami
        target: /data/backup
        read_only: true
    networks:
      - umami-restic-2-internet
    restart: unless-stopped

  umami-valkey:
    image: docker.io/valkey/valkey:8.1.5
    command:
      - valkey-server
      - --appendonly
      - "yes"
      - --requirepass
      - "${UMAMI_CACHE_PASSWORD}"
    volumes:
      - type: volume
        source: umami-valkey-vol
        target: /data
        volume:
          nocopy: false
    networks:
      - umami-2-valkey
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "valkey-cli"
        - "-a"
        - "${UMAMI_CACHE_PASSWORD}"
        - "ping"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  umami:
    init: true # https://github.com/krallin/tini#using-tini
    image: ghcr.io/umami-software/umami:3.2.0
    environment:
      DATABASE_URL: postgresql://${UMAMI_DATABASE_USER:-um}:${UMAMI_DATABASE_PASSWORD}@umami-postgres:5432/${UMAMI_DATABASE_DB:-um}
      REDIS_URL: redis://:${UMAMI_CACHE_PASSWORD}@umami-valkey:6379
      APP_SECRET: ${UMAMI_APP_SECRET}
      DISABLE_LOGIN: 1 # WARN: Requires proper Authelia middleware setup
      DISABLE_UPDATES: 1
    networks:
      - umami-2-internet
      - umami-2-postgres
      - umami-2-valkey
      - traefik-2-umami
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-umami"
      - "traefik.http.routers.umami.rule=Host(`${UMAMI_DOMAIN}`)"
      - "traefik.http.routers.umami.middlewares=authelia@docker"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.routers.umami.tls=true"
      - "traefik.http.routers.umami.tls.certresolver=letsencrypt"
      - "traefik.http.routers.umami.service=umami"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
    restart: unless-stopped
    depends_on:
      umami-postgres:
        condition: service_healthy
        restart: true
      umami-valkey:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Password manager
  vaultwarden-postgres:
    image: docker.io/library/postgres:16.9
    environment:
      POSTGRES_DB: ${VAULTWARDEN_DATABASE_DB:-vw}
      POSTGRES_USER: ${VAULTWARDEN_DATABASE_USER:-vw}
      POSTGRES_PASSWORD: ${VAULTWARDEN_DATABASE_PASSWORD}
    volumes:
      - type: volume
        source: vaultwarden-postgres-vol
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    networks:
      - vaultwarden-2-postgres
      - vaultwarden-pgdumper-2-postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${VAULTWARDEN_DATABASE_USER:-vw} -d ${VAULTWARDEN_DATABASE_DB:-vw}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  vaultwarden-pgdumper:
    image: docker.io/martlark/pg_dump:16.1
    environment:
      CRON_SCHEDULE: "1 * * * *"
      RETAIN_COUNT: 1
      PGHOST: "vaultwarden-postgres"
      POSTGRES_DB: ${VAULTWARDEN_DATABASE_DB:-vw}
      PGUSER: ${VAULTWARDEN_DATABASE_USER:-vw}
      POSTGRES_PASSWORD: ${VAULTWARDEN_DATABASE_PASSWORD}
    volumes:
      - type: bind
        source: /var/stor/vaultwarden/pgdump
        target: /dump
    networks:
      - vaultwarden-pgdumper-2-postgres
    restart: unless-stopped
    depends_on:
      vaultwarden-postgres:
        condition: service_healthy
        restart: true

  vaultwarden-restic:
    image: ghcr.io/lobaro/restic-backup-docker:v1.4.2
    environment:
      BACKUP_CRON: "52 * * * *" # Every hour at 52nd minute
      RESTIC_FORGET_ARGS: "--prune --keep-last 3 --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"
      RESTIC_PASSWORD: "${VAULTWARDEN_RESTIC_ENCRYPTION_KEY}"
      RESTIC_REPOSITORY: "s3:https://${VAULTWARDEN_RESTIC_S3_ENDPOINT}/${VAULTWARDEN_RESTIC_S3_BUCKET}"
      AWS_ACCESS_KEY_ID: "${VAULTWARDEN_RESTIC_S3_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${VAULTWARDEN_RESTIC_S3_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: /var/stor/vaultwarden
        target: /data/backup
        read_only: true
    networks:
      - vaultwarden-restic-2-internet
    restart: unless-stopped

  vaultwarden:
    image: docker.io/vaultwarden/server:1.34.3
    environment:
      DATABASE_URL: "postgresql://${VAULTWARDEN_DATABASE_USER:-vw}:${VAULTWARDEN_DATABASE_PASSWORD}@vaultwarden-postgres:5432/${VAULTWARDEN_DATABASE_DB:-vw}"
      DOMAIN: "https://${VAULTWARDEN_DOMAIN}"
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true
      INVITATIONS_ALLOWED: true
      ORG_CREATION_USERS: ${VAULTWARDEN_ORG_CREATION_USERS:-none}
      PASSWORD_HINTS_ALLOWED: false
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: ${VAULTWARDEN_SMTP_HOST:-}
      SMTP_FROM: ${VAULTWARDEN_SMTP_FROM:-}
      SMTP_FROM_NAME: ${VAULTWARDEN_FROM_NAME:-}
      SMTP_USERNAME: ${VAULTWARDEN_SMTP_USERNAME:-}
      SMTP_PASSWORD: ${VAULTWARDEN_STMP_PASSWORD:-}
    volumes:
      - type: bind
        source: /var/stor/vaultwarden/data
        target: /data
    networks:
      - vaultwarden-2-internet
      - vaultwarden-2-postgres
      - traefik-2-vaultwarden
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-vaultwarden"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    restart: unless-stopped
    depends_on:
      vaultwarden-postgres:
        condition: service_healthy
        restart: true

  # Drive
  sftpgo-postgres:
    image: docker.io/library/postgres:16.9
    environment:
      POSTGRES_DB: ${SFTPGO_DATABASE_DB:-sgo}
      POSTGRES_USER: ${SFTPGO_DATABASE_USER:-sgo}
      POSTGRES_PASSWORD: ${SFTPGO_DATABASE_PASSWORD}
    volumes:
      - type: volume
        source: sftpgo-postgres-vol
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    networks:
      - sftpgo-2-postgres
      - sftpgo-pgdumper-2-postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${SFTPGO_DATABASE_USER:-sgo} -d ${SFTPGO_DATABASE_DB:-sgo}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  sftpgo-pgdumper:
    image: docker.io/martlark/pg_dump:16.1
    environment:
      CRON_SCHEDULE: "1 * * * *"
      RETAIN_COUNT: 1
      PGHOST: "sftpgo-postgres"
      POSTGRES_DB: ${SFTPGO_DATABASE_DB:-sgo}
      PGUSER: ${SFTPGO_DATABASE_USER:-sgo}
      POSTGRES_PASSWORD: ${SFTPGO_DATABASE_PASSWORD}
    volumes:
      - type: bind
        source: /var/stor/sftpgo/pgdump
        target: /dump
    networks:
      - sftpgo-pgdumper-2-postgres
    restart: unless-stopped
    depends_on:
      sftpgo-postgres:
        condition: service_healthy
        restart: true

  sftpgo-restic:
    image: ghcr.io/lobaro/restic-backup-docker:v1.4.2
    environment:
      BACKUP_CRON: "52 4 * * *" # Every day at 04:52
      RESTIC_FORGET_ARGS: "--prune --keep-last 3 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"
      RESTIC_PASSWORD: "${SFTPGO_RESTIC_ENCRYPTION_KEY}"
      RESTIC_REPOSITORY: "s3:https://${SFTPGO_RESTIC_S3_ENDPOINT}/${SFTPGO_RESTIC_S3_BUCKET}"
      AWS_ACCESS_KEY_ID: "${SFTPGO_RESTIC_S3_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${SFTPGO_RESTIC_S3_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: /var/stor/sftpgo
        target: /data/backup
        read_only: true
    networks:
      - sftpgo-restic-2-internet
    restart: unless-stopped

  sftpgo:
    image: ghcr.io/drakkan/sftpgo:v2.6.6-distroless-slim
    extra_hosts:
      - "${AUTHELIA_DOMAIN}:172.19.0.253"
    environment:
      SFTPGO_DEFAULT_ADMIN_USERNAME: ${SFTPGO_ADMIN_USERNAME:-admin}
      SFTPGO_DEFAULT_ADMIN_PASSWORD: ${SFTPGO_ADMIN_PASSWORD}
      SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: true
      SFTPGO_DATA_PROVIDER__DRIVER: "postgresql"
      SFTPGO_DATA_PROVIDER__NAME: ${SFTPGO_DATABASE_DB:-sgo}
      SFTPGO_DATA_PROVIDER__HOST: "sftpgo-postgres"
      SFTPGO_DATA_PROVIDER__PORT: 5432
      SFTPGO_DATA_PROVIDER__USERNAME: ${SFTPGO_DATABASE_USER:-sgo}
      SFTPGO_DATA_PROVIDER__PASSWORD: ${SFTPGO_DATABASE_PASSWORD}
      SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: "sftpgo"
      SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: ${SFTPGO_OIDC_SECRET}
      SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: "https://${AUTHELIA_DOMAIN}"
      SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: "https://${SFTPGO_DOMAIN}"
      SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES: "openid,profile,email,sftpgo"
      SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD: "preferred_username"
      SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD: "sftpgo_role"
      SFTPGO_SMTP__HOST: ${SFTPGO_SMTP_HOST:-}
      SFTPGO_SMTP__PORT: ${SFTPGO_SMTP_PORT:-587}
      SFTPGO_SMTP__FROM: ${SFTPGO_SMTP_FROM:-}
      SFTPGO_SMTP__USER: ${SFTPGO_SMTP_USERNAME:-}
      SFTPGO_SMTP__PASSWORD: ${SFTPGO_SMTP_PASSWORD:-}
      SFTPGO_SMTP__ENCRYPTION: ${SFTPGO_SMTP_ENCRYPTION:-2}
    volumes:
      - type: bind
        source: /var/stor/sftpgo/internal
        target: /srv/sftpgo
      - type: bind
        source: /var/stor/sftpgo/storage
        target: /var/lib/sftpgo
    ports:
      - "2022:2022/tcp"
    networks:
      - sftpgo-2-internet
      - sftpgo-2-postgres
      - traefik-2-sftpgo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-sftpgo"
      - "traefik.http.routers.sftpgo.rule=Host(`${SFTPGO_DOMAIN}`)"
      - "traefik.http.routers.sftpgo.entrypoints=websecure"
      - "traefik.http.routers.sftpgo.tls=true"
      - "traefik.http.routers.sftpgo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sftpgo.service=sftpgo"
      - "traefik.http.services.sftpgo.loadbalancer.server.port=8080"
    restart: unless-stopped
    depends_on:
      sftpgo-postgres:
        condition: service_healthy
        restart: true

  # Workspace
  vikunja:
    image: docker.io/vikunja/vikunja:1.0.0-rc3
    extra_hosts:
      - "${AUTHELIA_DOMAIN}:172.19.1.253"
    environment:
      VIKUNJA_SERVICE_PUBLICURL: "https://${VIKUNJA_DOMAIN}"
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
      VIKUNJA_SERVICE_ENABLEUSERDELETION: false
      VIKUNJA_AUTH_OPENID_ENABLED: true
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_NAME: "Authelia"
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_AUTHURL: "https://${AUTHELIA_DOMAIN}"
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTID: "vikunja"
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET: ${VIKUNJA_SECRET}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_SCOPE: "openid profile email vikunja_scope"
      VIKUNJA_SERVICE_CUSTOMLOGOURL: ${VIKUNJA_LOGO}
      VIKUNJA_AUTH_LOCAL_ENABLED: false
    volumes:
      - type: volume
        source: vikunja-files-vol
        target: /app/vikunja/files
      - type: volume
        source: vikunja-db-vol
        target: /db
    networks:
      - vikunja-2-internet
      - traefik-2-vikunja
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-vikunja"
      - "traefik.http.routers.vikunja.rule=Host(`${VIKUNJA_DOMAIN}`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls=true"
      - "traefik.http.routers.vikunja.tls.certresolver=letsencrypt"
      - "traefik.http.routers.vikunja.service=vikunja"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
    restart: unless-stopped

  # BigBrotherDVR
  bigbrother:
    image: ghcr.io/blokadainfo/bigbrother:v0.0.1
    environment:
      RECORDINGS_PATH: "/recordings" # Same as volume target
      RECORDINGS_LIMIT: 1000 # In GB
      RECORDINGS_DRYRUN: false
      STREAMS_0_SRC: ${BIGBROTHER_STREAMS_0_SRC}
      STREAMS_0_DST: ${BIGBROTHER_STREAMS_0_DST}
      STREAMS_1_SRC: ${BIGBROTHER_STREAMS_1_SRC}
      STREAMS_1_DST: ${BIGBROTHER_STREAMS_1_DST}
      STREAMS_2_SRC: ${BIGBROTHER_STREAMS_2_SRC}
      STREAMS_2_DST: ${BIGBROTHER_STREAMS_2_DST}
      STREAMS_3_SRC: ${BIGBROTHER_STREAMS_3_SRC}
      STREAMS_3_DST: ${BIGBROTHER_STREAMS_3_DST}
      STREAMS_4_SRC: ${BIGBROTHER_STREAMS_4_SRC}
      STREAMS_4_DST: ${BIGBROTHER_STREAMS_4_DST}
    volumes:
      - type: bind
        source: /var/stor/dvr
        target: /recordings # Same as env RECORDINGS_PATH
    networks:
      - bigbrother-2-internet
    restart: unless-stopped

networks:
  wireguard-2-internet:
    internal: false
  wireguard-2-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.15.0/24"
          gateway: "172.16.15.254"
  traefik-2-internet:
    internal: false
  traefik-2-wireguard:
    internal: true
  traefik-2-lldap:
    internal: true
  traefik-2-authelia:
    internal: true
  traefik-2-umami:
    internal: true
  traefik-2-vaultwarden:
    internal: true
  traefik-2-sftpgo:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
          gateway: "172.19.0.254"
  traefik-2-vikunja:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.1.0/24"
          gateway: "172.19.1.254"
  cloudflared-2-internet:
    internal: false
  cloudflared-2-traefik:
    internal: true
  lldap-2-internet:
    internal: false
  lldap-2-postgres:
    internal: true
  lldap-pgdumper-2-postgres:
    internal: true
  lldap-restic-2-internet:
    internal: false
  authelia-2-internet:
    internal: false
  authelia-2-valkey:
    internal: true
  authelia-2-postgres:
    internal: true
  authelia-2-lldap:
    internal: true
  authelia-pgdumper-2-postgres:
    internal: true
  authelia-restic-2-internet:
    internal: false
  umami-2-internet:
    internal: false
  umami-2-postgres:
    internal: true
  umami-pgdumper-2-postgres:
    internal: true
  umami-restic-2-internet:
    internal: false
  umami-2-valkey:
    internal: true
  vaultwarden-2-internet:
    internal: false
  vaultwarden-2-postgres:
    internal: true
  vaultwarden-pgdumper-2-postgres:
    internal: true
  vaultwarden-restic-2-internet:
    internal: false
  sftpgo-2-internet:
    internal: false
  sftpgo-2-postgres:
    internal: true
  sftpgo-pgdumper-2-postgres:
    internal: true
  sftpgo-restic-2-internet:
    internal: false
  vikunja-2-internet:
    internal: false
  bigbrother-2-internet:
    internal: false

volumes:
  wireguard-conf-vol:
  traefik-logs-vol:
  traefik-acme-vol:
  lldap-postgres-vol:
  authelia-valkey-vol:
  authelia-postgres-vol:
  umami-postgres-vol:
  umami-valkey-vol:
  vaultwarden-postgres-vol:
  sftpgo-postgres-vol:
  vikunja-files-vol:
  vikunja-db-vol:
